// +build ignore

// This program generates list.go. It can be invoked by running
// go generate

package main

import (
	"bufio"
	"bytes"
	"compress/zlib"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/globalsign/publicsuffix"
)

func main() {
	var listRetriever publicsuffix.GitHubListRetriever

	var latestTag, err = listRetriever.GetLatestReleaseTag()
	if err != nil {
		fmt.Println(fmt.Sprintf("error while retrieving last commit information: %s", err.Error()))
		os.Exit(1)
	}

	var rawList io.Reader
	rawList, err = listRetriever.GetList(latestTag)
	if err != nil {
		fmt.Println(fmt.Sprintf("error while retrieving Public Suffix List latest release: %s", err.Error()))
		os.Exit(1)
	}

	var file *os.File
	file, err = os.Create("list.go")
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}

	if err = printFile(file, rawList, latestTag); err != nil {
		fmt.Println(fmt.Sprintf("error while generating code: %s", err.Error()))
		os.Exit(1)
	}
}

func printFile(w io.Writer, r io.Reader, release string) error {
	fmt.Fprintf(w, "// generated by go run gen.go; DO NOT EDIT\n\n")
	fmt.Fprintf(w, "package publicsuffix\n\nvar initialRelease = `%s`\n\n", release)

	var bufferReader = bufio.NewReader(r)
	var listBuffer bytes.Buffer

	for {
		var line, err = bufferReader.ReadString('\n')
		if err != nil {
			if err == io.EOF {
				break
			}
			fmt.Fprintf(w, "`\n")
			return err
		}

		line = strings.TrimSpace(line)

		if line == "" || strings.HasPrefix(line, "//") {
			continue
		}

		listBuffer.WriteString(fmt.Sprintf("%s\n", line))
	}

	// Compression zlib
	var zlibBuffer bytes.Buffer
	var zlibWriter = zlib.NewWriter(&zlibBuffer)
	zlibWriter.Write(listBuffer.Bytes())
	zlibWriter.Close()

	fmt.Fprintf(w, "var listBytes = []byte{")

	for _, b := range zlibBuffer.Bytes() {
		fmt.Fprintf(w, "0x%01X,", b)
	}

	fmt.Fprintf(w, "}\n")

	return nil
}
